### ISSUE TITLE
Merge patterns into main Nextflow docs

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/patterns#27]
The Nextflow patterns provide a lot of value to users at every level. I think they would have more visibility if they were part of the main Nextflow docs, since that seems to be the starting point for most people.

What do you think @pditommaso

**Comment by pditommaso** [comment]
It makes sense. It is something we need to coordinate with @ewels. For me the update of patterns and [process docs](https://www.nextflow.io/docs/latest/process.html) to DSL2 syntax is top priority

**Comment by ewels** [comment]
I definitely agree 👍🏻 I think this should be done as part of the Nextflow website v2 effort though, which is a fairly long term target.

@pditommaso - looks like @bentsherman has already updated all the patterns 2 months ago, just waiting to be merged 👀 👉🏻 https://github.com/nextflow-io/patterns/pull/26

**Comment by bentsherman** [comment]
After discussing with Phil and the Nextflow website team, we have a tentative plan for consolidating Nextflow web resources, which is much broader than simply merging the patterns into the reference docs. Therefore I am closing this issue in favor of that plan.
