### ISSUE TITLE
Typo for "Process when empty"?

### ISSUE THREAD

**Issue by nick-youngblut** [nextflow-io/patterns#38]
Current example for [process-when-empty](https://nextflow-io.github.io/patterns/process-when-empty/):

```
params.inputs = ''

process foo {
  debug true  
  input:
  val x
  when:
  x ## 'EMPTY'

  script:
  '''
  echo hello
  ''' 
}

workflow {
  reads_ch = params.inputs
    ? Channel.fromPath(params.inputs, checkIfExists:true)
    : Channel.empty()

  reads_ch \
    | ifEmpty { 'EMPTY' } \
    | foo
}
```

I'm guessing that `x ## 'EMPTY'`  should be `x == 'EMPTY'`

**Comment by pditommaso** [comment]
Yes, definitively. Thanks for reporting it

**Comment by mribeirodantas** [comment]
Fixed by https://github.com/nextflow-io/patterns/commit/9d66fbd39813f5b1139ea0cafceb02018b0c0109
