### ISSUE TITLE
blast-parallel.nf adding makeblastdb process

### ISSUE THREAD

**Issue by mictadlo** [nextflow-io/patterns#5]
Hi,
Would you be able to add [makeblastdb](https://www.nextflow.io/docs/latest/process.html?highlight=makeblastdb) process to [blast-parallel.nf](https://github.com/nextflow-io/examples/blob/master/blast-parallel.nf)?

```
genomes = Channel.fromPath(params.genomes)

process formatBlastDatabases {

  storeDir '/db/genomes'

  input:
  file species from genomes

  output:
  file "${dbName}.*" into blastDb

  script:
  dbName = species.baseName
  """
  makeblastdb -dbtype nucl -in ${species} -out ${dbName}
  """
}
```

Thank you in advance.

Michal

**Comment by pditommaso** [comment]
Sorry, I've seen this only now. Is this still an open issue ?

**Comment by mictadlo** [comment]
Yes, it is.

**Comment by mictadlo** [comment]
Unfortunately, I still do not know how to combine makeblastdb and [blast](https://github.com/nextflow-io/blast-example/blob/master/main.nf) with nextflow together. Is there any HOWTO?

**Comment by pditommaso** [comment]
Please post the question in the [discussion forum](https://groups.google.com/forum/#!forum/nextflow).

**Comment by Lcornet** [comment]
Hi, 

Same issue, did you find a solution? I don't find the discussion in the forum.

**Comment by mictadlo** [comment]
No, I didn't, and I forgot to post it to the forum. Maybe do you want to post it?
