### ISSUE TITLE
Blast example stuck

### ISSUE THREAD

**Issue by huang-ying** [nextflow-io/patterns#6]
I'm trying to run blast.nf in my workstation, blast_result and top_hits have been generated, then the project stuck. Any possible reason?

nextflow run examples/blast.nf -with-docker -with-report -with-timeline
N E X T F L O W  ~  version 0.27.0
Launching `examples/blast.nf` [small_nightingale] - revision: 7b4b740be4
[warm up] executor > local
[94/2ab84a] Submitted process > blast (1)

nextflow info
  Version: 0.27.0 build 4751
  Modified: 09-01-2018 10:18 UTC (05:18 EDT)
  System: Linux 3.10.0-514.10.2.el7.x86_64
  Runtime: Groovy 2.4.13 on OpenJDK 64-Bit Server VM 1.8.0_121-b13
  Encoding: UTF-8 (UTF-8)

**Comment by pditommaso** [comment]
I've seen this problem when there's not enough memory to run the container. Could it be the case?
